### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by VictoriaMarull** [VictoriaMarull/viajerosiconicos#1]
- [ ] Estructura del paquete
- [ ] Repositorio local
- [ ] Repositorio remoto
- [ ] Titulo
- [ ] Descripcion
- [ ] Autores
- [ ] Carga data set
- [ ] Funcion 1
- [ ] Funcion 2 
- [ ] Funcion 3
- [ ] Documentacion funciones
- [ ] Documentacion datos
- [ ] README completo
- [ ] viñeta que explique uso de funciones
- [ ] Pagina web
- [ ] Test que cubre al menos el 75% de codigo de las funciones
- [ ] GitHub action que revisa la covertura de los tests
- [ ] El paquete pasa R CMD checks
- [ ] El paquete tiene una GitHub action que chequea el paquete en distintos sistemas operativos
- [ ] Licencias
- [ ] Instrucciones del README: contribucion, autores, instalacion.
